// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package outsmarty

type Answer struct {
	ID         int64
	QuestionID int64
	PlayerID   int64
	AnswerText string
	IsCorrect  bool
}

type Game struct {
	ID           int64
	ThemeID      int64
	NumRounds    int64
	CurrentRound int64
}

type GamePlayer struct {
	ID       int64
	GameID   int64
	PlayerID int64
	Points   int64
}

type GameRound struct {
	ID          int64
	GameID      int64
	RoundNumber int64
	QuestionID  int64
}

type Player struct {
	ID   int64
	Name string
}

type Question struct {
	ID            int64
	ThemeID       int64
	QuestionText  string
	CorrectAnswer string
}

type Theme struct {
	ID   int64
	Name string
}
